export interface SourceFile {
  path: string
  source: string
  compilerOptions?: {
    jsx?: boolean
    typescript?: boolean
  }
}

export interface CheckRequest {
  projectId: string
  generation: number
  sources: SourceFile[]
  /** TypeFacts v2 closure generated by a TypeScript host for these sources. */
  typeFacts: unknown
}

/** Runs the Oxc, Solid compiler, reactive IR, and solver pipeline in-process. */
export declare function checkSync(requestJson: string): string
